const events=[
{id:"e1",title:"Inter-College Innovation Sprint",org:"SAMPLE · MP INNOVATION",cat:"Hackathon",format:"Offline",college:"SGSITS, Indore",date:"Example date · verify first",desc:"Demo listing for a team-based build sprint focused on useful student solutions.",icon:"⌘",cls:"hack",url:"https://www.sgsits.ac.in/"},
{id:"e2",title:"Design Thinking Studio",org:"SAMPLE · CAMPUS WORKSHOP",cat:"Design",format:"Offline",college:"DAVV, Indore",date:"Example date · verify first",desc:"Demo creative workshop concept for sketching ideas and prototyping.",icon:"✳",cls:"design",url:"https://www.dauniv.ac.in/"},
{id:"e3",title:"AI & Emerging Tech Workshop",org:"SAMPLE · LEARNING SESSION",cat:"Workshop",format:"Hybrid",college:"IIT Indore",date:"Example date · verify first",desc:"Illustrative technical learning event. This is not a confirmed IIT Indore event.",icon:"⌁",cls:"workshop",url:"https://www.iiti.ac.in/"},
{id:"e4",title:"Student Startup Pitch Day",org:"SAMPLE · ENTREPRENEURSHIP",cat:"Competition",format:"Offline",college:"Indore · Multi-college",date:"Example date · verify first",desc:"Demo opportunity to practise pitching a problem, solution and impact.",icon:"↗",cls:"competition",url:"https://www.iiti.ac.in/"},
{id:"e5",title:"Careers Beyond the Classroom",org:"SAMPLE · CAREER TALK",cat:"Talk",format:"Online",college:"Open to MP students",date:"Example date · verify first",desc:"Sample online talk concept about portfolios, projects and career exploration.",icon:"◉",cls:"talk",url:"https://www.dauniv.ac.in/"},
{id:"e6",title:"Build for a Greener City",org:"SAMPLE · SUSTAINABILITY",cat:"Competition",format:"Hybrid",college:"Madhya Pradesh · Multi-college",date:"Example date · verify first",desc:"Sample challenge concept for cleaner, more accessible campuses.",icon:"♧",cls:"workshop",url:"https://www.sgsits.ac.in/"}];
const $=id=>document.getElementById(id);let saved=[];try{saved=JSON.parse(localStorage.getItem("cp-saved")||"[]")}catch{}let installPrompt=null,timer;
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("toast").classList.remove("show"),2500)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function card(e){let yes=saved.includes(e.id);return `<article class="event"><div class="banner ${e.cls}"><span class="symbol">${e.icon}</span><span class="tag">${e.cat}</span><button class="save ${yes?"on":""}" data-save="${e.id}" aria-label="Save event">${yes?"★":"☆"}</button></div><div class="content"><div class="org">${e.org}</div><h3>${e.title}</h3><p class="desc">${e.desc}</p><div class="details"><span>⌖ ${e.college}</span><span>◷ ${e.date}</span></div><div class="foot"><span class="pill">${e.format}</span><a href="${e.url}" target="_blank" rel="noopener noreferrer">Official site ↗</a></div></div></article>`}
function render(){let q=$("search").value.toLowerCase().trim(),cat=$("category").value,fmt=$("format").value,col=$("college").value;let list=events.filter(e=>(!q||[e.title,e.org,e.cat,e.college,e.desc].join(" ").toLowerCase().includes(q))&&(cat==="all"||cat===e.cat)&&(fmt==="all"||fmt===e.format)&&(col==="all"||col===e.college));$("events").innerHTML=list.map(card).join("");$("result-count").textContent=`Showing ${list.length} ${list.length===1?"opportunity":"opportunities"}`;$("empty").hidden=!!list.length;renderSaved()}
function renderSaved(){$("saved-count").textContent=saved.length;let list=events.filter(e=>saved.includes(e.id));$("saved-list").innerHTML=list.length?list.map(e=>`<div class="saved-item"><span>${e.icon}</span><div><strong>${e.title}</strong><small>${e.college} · ${e.cat}</small></div><button data-save="${e.id}">Remove</button></div>`).join(""):"Nothing saved yet. Tap ☆ on an event."}
document.addEventListener("click",ev=>{let b=ev.target.closest("[data-save]");if(!b)return;let id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("cp-saved",JSON.stringify(saved));render();toast(saved.includes(id)?"Saved to your list.":"Removed from your list.")});
["search","category","format","college"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",render));
$("college").innerHTML+=[...new Set(events.map(e=>e.college))].map(c=>`<option>${c}</option>`).join("");
$("notify").addEventListener("click",async()=>{if(!("Notification"in window)){toast("This browser doesn't support notifications.");return}if(Notification.permission==="denied"){toast("Notifications blocked in browser settings.");return}try{let p=await Notification.requestPermission();if(p==="granted"){toast("Permission enabled. Scheduled reminders will be added in a later version.");new Notification("CampusPulse",{body:"Notifications are enabled for this demo."})}else toast("Notifications not enabled.")}catch{toast("Open through localhost or HTTPS to test notifications.")}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("install").hidden=false});
$("install").addEventListener("click",async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("install").hidden=true}else toast("Use browser menu → Install app / Add to Home Screen.")});
if("serviceWorker"in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
render();