````javascript
const events=[
{id:"e1",title:"AICTE Internship Opportunities",org:"AICTE Internship Portal",cat:"Internship",format:"Online",college:"Open to MP students",date:"Check official portal",desc:"Explore internships and check eligibility, duration and deadlines before applying.",icon:"↗",cls:"blue",url:"https://internship.aicte-india.org/"},
{id:"e2",title:"MyGov Design Competitions",org:"MyGov India",cat:"Design",format:"Online",college:"Open to eligible participants",date:"Check each contest deadline",desc:"Explore official design contests and read the rules before submitting your entry.",icon:"✳",cls:"purple",url:"https://www.mygov.in/home/do"},
{id:"e3",title:"National Scholarship Portal",org:"Government of India",cat:"Scholarship",format:"Online",college:"Eligibility varies by scheme",date:"Check current application dates",desc:"Find scholarship schemes and verify eligibility, documents and application deadlines.",icon:"☆",cls:"green",url:"https://scholarships.gov.in/"},
{id:"e4",title:"MP Scholarship Information",org:"Government of Madhya Pradesh",cat:"Scholarship",format:"Online",college:"Eligible MP students",date:"Check current scheme dates",desc:"Review official scholarship information and confirm the correct application portal.",icon:"↗",cls:"blue",url:"https://services.india.gov.in/"},
{id:"e5",title:"Smart India Hackathon",org:"Ministry of Education Innovation Cell",cat:"Hackathon",format:"Hybrid",college:"Eligibility varies by edition",date:"Check official announcement",desc:"Check the latest edition, participation rules, team requirements and registration dates.",icon:"⌘",cls:"orange",url:"https://www.sih.gov.in/"},
{id:"e6",title:"AICTE Events and Announcements",org:"AICTE",cat:"Competition",format:"Online",college:"Eligibility varies by event",date:"Check official announcement",desc:"Explore current announcements and verify each event before applying.",icon:"◎",cls:"green",url:"https://www.aicte-india.org/"}
];```
````
;
const $=id=>document.getElementById(id);let saved=[];try{saved=JSON.parse(localStorage.getItem("cp-saved")||"[]")}catch{}let installPrompt=null,timer;
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("toast").classList.remove("show"),2500)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function card(e){let yes=saved.includes(e.id);return `<article class="event"><div class="banner ${e.cls}"><span class="symbol">${e.icon}</span><span class="tag">${e.cat}</span><button class="save ${yes?"on":""}" data-save="${e.id}" aria-label="Save event">${yes?"★":"☆"}</button></div><div class="content"><div class="org">${e.org}</div><h3>${e.title}</h3><p class="desc">${e.desc}</p><div class="details"><span>⌖ ${e.college}</span><span>◷ ${e.date}</span></div><div class="foot"><span class="pill">${e.format}</span><a href="${e.url}" target="_blank" rel="noopener noreferrer">Official site ↗</a></div></div></article>`}
function render(){let q=$("search").value.toLowerCase().trim(),cat=$("category").value,fmt=$("format").value,col=$("college").value;let list=events.filter(e=>(!q||[e.title,e.org,e.cat,e.college,e.desc].join(" ").toLowerCase().includes(q))&&(cat==="all"||cat===e.cat)&&(fmt==="all"||fmt===e.format)&&(col==="all"||col===e.college));$("events").innerHTML=list.map(card).join("");$("result-count").textContent=`Showing ${list.length} ${list.length===1?"opportunity":"opportunities"}`;$("empty").hidden=!!list.length;renderSaved()}
function renderSaved(){$("saved-count").textContent=saved.length;let list=events.filter(e=>saved.includes(e.id));$("saved-list").innerHTML=list.length?list.map(e=>`<div class="saved-item"><span>${e.icon}</span><div><strong>${e.title}</strong><small>${e.college} · ${e.cat}</small></div><button data-save="${e.id}">Remove</button></div>`).join(""):"Nothing saved yet. Tap ☆ on an event."}
document.addEventListener("click",ev=>{let b=ev.target.closest("[data-save]");if(!b)return;let id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("cp-saved",JSON.stringify(saved));render();toast(saved.includes(id)?"Saved to your list.":"Removed from your list.")});
["search","category","format","college"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",render));
$("college").innerHTML+=[...new Set(events.map(e=>e.college))].map(c=>`<option>${c}</option>`).join("");
$("notify").addEventListener("click",async()=>{if(!("Notification"in window)){toast("This browser doesn't support notifications.");return}if(Notification.permission==="denied"){toast("Notifications blocked in browser settings.");return}try{let p=await Notification.requestPermission();if(p==="granted"){toast("Permission enabled. Scheduled reminders will be added in a later version.");new Notification("CampusPulse",{body:"Notifications are enabled for this demo."})}else toast("Notifications not enabled.")}catch{toast("Open through localhost or HTTPS to test notifications.")}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("install").hidden=false});
$("install").addEventListener("click",async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("install").hidden=true}else toast("Use browser menu → Install app / Add to Home Screen.")});
if("serviceWorker"in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
render();
